image: ubuntu:latest
variables:
  INO_FILE: terminal.ino

before_script:
  - apt-get update
  - apt-get install curl -y
  - cd ~
  - curl -L https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh > install.sh
  - sh install.sh
  - export PATH=$PATH:~/bin

  - printf "board_manager:\n  additional_urls:\n    - https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json\n" > .arduino-cli.yaml
  - arduino-cli core update-index --config-file .arduino-cli.yaml
  - arduino-cli core install Seeeduino:samd --config-file .arduino-cli.yaml

  - arduino-cli lib install PubSubClient@2.8.0
  - arduino-cli lib install 'Seeed Arduino rpcWiFi'
  - cd Arduino/libraries

  - apt-get install git -y

  - git clone https://github.com/Seeed-Studio/Seeed_Arduino_UltrasonicRanger.git
  - git clone https://github.com/Seeed-Studio/Grove_Temperature_And_Humidity_Sensor.git
  - git clone https://github.com/adafruit/Adafruit_NeoPixel.git


stages:
  - build

compile:
  stage: build
  tags:
    - docker
  script:                                                       
    - arduino-cli lib list
    - cd ${CI_PROJECT_DIR}/Terminal
    - pwd
    - ls -l
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal $INO_FILE
